### ISSUE TITLE
update npm package

### ISSUE THREAD

**Issue by balaclark** [tomgco/robots.txt#3]
Hi, a while ago you merged https://github.com/tomgco/robots.txt/pull/2, can you publish this in npm so we can get the update in our projects?

**Comment by tomgco** [comment]
Totally fell off of my radar, sorry about that. `1.1.0` has been released.

I have added you as a collaborator, feel free to merge any pr's you wish =]

**Comment by tomgco** [comment]
@balaclark Let me know what your npm username is so I can add you to the npm owners so you can publish.

**Comment by balaclark** [comment]
Somehow I missed this message, thanks for adding me! My npm username is also "balaclark" https://www.npmjs.org/~balaclark

**Comment by tomgco** [comment]
You are listed as an owner: https://www.npmjs.org/package/robots.txt
